In [2]:
import pandas as pd
import numpy as np 
import warnings
warnings.filterwarnings('ignore')

We have imported the necesary libraries,now we will load the dataset that we have extracted from various sources.

In [11]:
df=pd.read_excel(r'C:\Nimish\Capstone-phase1-data.xls')
df

,State/UT,Year,population(total),Area (km2),Literacy rate,total literate population,Attempt to murder,Murder,Rape,Kidnapping and abduction,...,Cruelty by husband or his relatives,Importation of girls from other countries,Other IPC crimes,Total IPC crimes,Total Crimes,tot_crimes_sc,total crime against women,Total crime against children,Total crimes against STs,Crime Rate
0,A& N ISLANDS,2001,356650,8249,81.30,253135.0,0,13,3,2,...,9,0,323,658,1386,0,34.0,0.0,1.0,187.757760
1,ANDHRA PRADESH,2001,75728401,275045,60.47,39934323.0,1555,2602,871,1182,...,5791,7,34344,130089,278982,2933,13669.0,270.0,512.0,173.698055
2,ARUNACHAL PRADESH,2001,1098328,83743,54.34,484785.0,53,83,33,83,...,11,0,618,2342,5243,0,180.0,0.0,72.0,217.834500
3,ASSAM,2001,26638600,78438,63.25,14015354.0,481,1356,817,1480,...,1248,0,9315,36877,81418,6,4048.0,18.0,0.0,140.759800
4,BIHAR,2001,82879911,94163,47.00,31109577.0,3419,3643,888,2159,...,1558,83,36667,88432,189612,1303,4489.0,83.0,83.0,103.458500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,TAMIL NADU,2012,73141715,130058,80.88,53274562.0,2954,1949,737,1945,...,1965,0,124176,200474,415626,1647,6381.0,1036.0,27.0,274.058370
416,TRIPURA,2012,3718947,10486,80.89,2897340.0,79,124,229,139,...,858,0,1742,6264,13461,76,1559.0,20.0,29.0,167.395800
417,UTTAR PRADESH,2012,202934265,240928,67.98,118889202.0,4811,4966,1963,8878,...,7661,0,68538,198093,444403,6202,23033.0,6033.0,44.0,96.323400
418,UTTARAKHAND,2012,10279517,53483,79.22,7100774.0,161,217,148,297,...,368,0,2118,8882,20122,33,1055.0,122.0,3.0,89.653300
419,WEST BENGAL,2012,92460379,88752,76.88,63274096.0,2854,2252,2046,5117,...,19865,12,64482,161427,353008,85,30585.0,1706.0,91.0,176.683700

Data for the population,area of each state and literacy rate of each state have been collected from the different websites manually. The data was available for the year #2001 and #2011 for population, area and literacy rate of each state. So, necassary calculations and assumptions were made in order to achive the data for the year #2002 to #2010 & year #2012. **For example Andhra Pradesh's population icreased around 11% from 2001 to 2011 so we increased around 1% for every year to achieve the same.** Several websites were used in order to fetch the data for the same. Some of them are:-

- https://en.wikipedia.org/wiki/List_of_states_in_India_by_past_population
- https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area
- https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate
- https://socialjustice.gov.in/common/76669
- http://cyberjournalist.org.in/census/cenindia.html
- https://www.indiastat.com/specimen-tables/geographical-data
- https://www.wbhealth.gov.in/other_files/2007/14_5.html
- https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_population